export const matchs = [
    {
        id: 1,
        name: 'Manchester United vs Liverpool',
        date: new Date('2024-11-15T20:00:00Z'),
        team1Id: 1,
        team2Id: 2,
        stadiumId: 1, // Example stadium ID
        mainEvent: true,
    },
    {
        id: 2,
        name: 'Arsenal vs Manchester City',
        date: new Date('2024-11-16T18:30:00Z'),
        team1Id: 3,
        team2Id: 4,
        stadiumId: 2, // Example stadium ID
        mainEvent: false,
    },
    {
        id: 3,
        name: 'Chelsea vs Tottenham Hotspur',
        date: new Date('2024-11-17T20:00:00Z'),
        team1Id: 5,
        team2Id: 6,
        stadiumId: 3,
        mainEvent: true,
    },
    {
        id: 4,
        name: 'Newcastle United vs Aston Villa',
        date: new Date('2024-11-18T19:00:00Z'),
        team1Id: 7,
        team2Id: 8,
        stadiumId: 4,
        mainEvent: false,
    },
    {
        id: 5,
        name: 'Everton vs Leicester City',
        date: new Date('2024-11-19T17:30:00Z'),
        team1Id: 9,
        team2Id: 10,
        stadiumId: 5,
        mainEvent: false,
    },
    {
        id: 6,
        name: 'Ipswich Town vs Southampton',
        date: new Date('2024-11-20T20:00:00Z'),
        team1Id: 11,
        team2Id: 12,
        stadiumId: 6,
        mainEvent: false,
    },
    {
        id: 7,
        name: 'West Ham United vs Wolverhampton Wanderers',
        date: new Date('2024-11-21T19:00:00Z'),
        team1Id: 13,
        team2Id: 14,
        stadiumId: 7,
        mainEvent: true,
    },
    {
        id: 8,
        name: 'Fulham vs Brighton & Hove Albion',
        date: new Date('2024-11-22T20:30:00Z'),
        team1Id: 15,
        team2Id: 16,
        stadiumId: 8,
        mainEvent: false,
    },
    {
        id: 9,
        name: 'Brentford FC vs AFC Bournemouth',
        date: new Date('2024-11-23T18:00:00Z'),
        team1Id: 17,
        team2Id: 18,
        stadiumId: 9,
        mainEvent: false,
    },
    {
        id: 10,
        name: 'Nottingham Forest FC vs Crystal Palace FC',
        date: new Date('2024-11-24T19:30:00Z'),
        team1Id: 19,
        team2Id: 20,
        stadiumId: 10,
        mainEvent: true,
    },
];
