export const teams = [
    {
        id: 1,
        name: 'Manchester United',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249128/ticketster/team/ud3ztfsgeb8g4saqqarm.png',
        stadiumId: 1,
        country: 'England',
    },
    {
        id: 2,
        name: 'Liverpool',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249126/ticketster/team/iub9yxs4ky85msplac5o.png',
        stadiumId: 2,
        country: 'England',
    },
    {
        id: 3,
        name: 'Arsenal',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249123/ticketster/team/e0llh9xf3e0zsneqgat3.png',
        stadiumId: 3,
        country: 'England',
    },
    {
        id: 4,
        name: 'Manchester City',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249126/ticketster/team/axnwbgrjyotex73pknpr.png',
        stadiumId: 4,
        country: 'England',
    },
    {
        id: 5,
        name: 'Chelsea',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249123/ticketster/team/g6olud3ueio0uyn19aoi.png',
        stadiumId: 5,
        country: 'England',
    },
    {
        id: 6,
        name: 'Tottenham Hotspur',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249128/ticketster/team/csdyqitzhu7ltxoaixqo.png',
        stadiumId: 6,
        country: 'England',
    },
    {
        id: 7,
        name: 'Newcastle United',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249127/ticketster/team/alfqeue0us6bz3rfa8xp.png',
        stadiumId: 7,
        country: 'England',
    },
    {
        id: 8,
        name: 'Aston Villa',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249122/ticketster/team/wgdtbh4efmzpppxf7cho.png',
        stadiumId: 8,
        country: 'England',
    },
    {
        id: 9,
        name: 'Everton',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249126/ticketster/team/s3zjc2n0rqycbu49lrlm.png',
        stadiumId: 9,
        country: 'England',
    },
    {
        id: 10,
        name: 'Leicester City',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249123/ticketster/team/dhdsgklliclsex3wxfwh.png',
        stadiumId: 10,
        country: 'England',
    },
    {
        id: 11,
        name: 'Ipswich Town',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249122/ticketster/team/srp2ih9jn7mqeepgzwz1.png',
        stadiumId: 11,
        country: 'England',
    },
    {
        id: 12,
        name: 'Southampton',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249128/ticketster/team/lhebfzkn1ojvt7ukyrlx.png',
        stadiumId: 12,
        country: 'England',
    },
    {
        id: 13,
        name: 'West Ham United',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249127/ticketster/team/l6fjm6s4v6iouk28yym8.png',
        stadiumId: 13,
        country: 'England',
    },
    {
        id: 14,
        name: 'Wolverhampton Wanderers',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249128/ticketster/team/gdmn19a14vlcjspb6tr5.png',
        stadiumId: 14,
        country: 'England',
    },
    {
        id: 15,
        name: 'Fulham',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249126/ticketster/team/mxikp8olevdw2qquptvd.png',
        stadiumId: 15,
        country: 'England',
    },
    {
        id: 16,
        name: 'Brighton & Hove Albion',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249124/ticketster/team/luumsv1j9ylafnsebwag.png',
        stadiumId: 16,
        country: 'England',
    },
    {
        id: 17,
        name: 'Brentford FC',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249123/ticketster/team/wwvaj1em35yfsj8pilw0.png',
        stadiumId: 17,
        country: 'England',
    },
    {
        id: 18,
        name: 'AFC Bournemouth',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249123/ticketster/team/uvgo6gk7r5jauunsucj8.png',
        stadiumId: 18,
        country: 'England',
    },
    {
        id: 19,
        name: 'Nottingham Forest FC',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249127/ticketster/team/vgkl9plswhtsyqjg5zyb.png',
        stadiumId: 19,
        country: 'England',
    },
    {
        id: 20,
        name: 'Crystal Palace FC',
        image: 'https://res.cloudinary.com/dnx415rjl/image/upload/v1731249124/ticketster/team/pwhh4w0ylejv3c9wcewv.png',
        stadiumId: 20,
        country: 'England',
    },
];
